# 🔍 Explorando matrices y operaciones básicas

## 📘 Contexto  
El propósito de esta actividad es poner en práctica la creación y manipulación de matrices en NumPy, así como la aplicación de operaciones básicas y la comprensión del comportamiento de la indexación.

## ✅ Consigna  
Crea una matriz 3×3 utilizando `np.array()` a partir de estas listas. Luego, aplica operaciones matemáticas básicas (suma, resta y multiplicación por un escalar) y realiza una selección condicional de elementos mayores a cinco. Finalmente, analiza si el resultado de una asignación es una copia o una referencia.

## 🧭 Paso a paso  

1. Importa la librería **NumPy** como `np`.  
2. Crea una matriz `A` de 3×3 con números enteros del 1 al 9.  
3. Realiza las siguientes operaciones:  
   - Suma 10 a cada elemento de la matriz.  
   - Multiplica la matriz por 2.  
   - Extrae los elementos mayores a 5 utilizando selección condicional.  
4. Asigna la matriz a una nueva variable: `B = A`. Modifica el valor de `B`.  
   - ¿Cambió también `A`?  
   - Ahora usa `B = A.copy()` y repite la modificación. ¿Qué ocurrió con `A` esta vez?


In [1]:
import numpy as np

# Crear la matriz A de 3x3 con números del 1 al 9
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print("Matriz original A:")
print(A)

# Sumar 10 a cada elemento
A_suma = A + 10
print("\nA + 10:")
print(A_suma)

# Multiplicar la matriz por 2
A_multi = A * 2
print("\nA * 2:")
print(A_multi)

# Selección condicional: elementos mayores a 5
condicion = A > 5
print("\nElementos mayores a 5:")
print(A[condicion])

# Asignación directa (referencia)
B = A
B[0, 0] = 100
print("\nDespués de modificar B (referencia):")
print("B:")
print(B)
print("A también se modifica:")
print(A)

# Asignación por copia
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])  # Reestablecer A
B = A.copy()
B[0, 0] = 200
print("\nDespués de modificar B (copia):")
print("B:")
print(B)
print("A no se modifica:")
print(A)


Matriz original A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

A + 10:
[[11 12 13]
 [14 15 16]
 [17 18 19]]

A * 2:
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Elementos mayores a 5:
[6 7 8 9]

Después de modificar B (referencia):
B:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]
A también se modifica:
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]

Después de modificar B (copia):
B:
[[200   2   3]
 [  4   5   6]
 [  7   8   9]]
A no se modifica:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# 🧪 Generación de datos y redimensionado

## 📌 Contexto
Esta actividad busca fortalecer el dominio sobre las funciones predefinidas para crear arreglos, generar datos de prueba y reestructurar su forma utilizando `reshape()`.

## 📝 Consigna
Utiliza funciones de NumPy como `np.arange()`, `np.linspace()` y `np.random.randint()` para generar distintos tipos de arreglos. Luego, redimensiónalos con `reshape()` y aplica funciones matemáticas sobre ellos.

## 🧭 Paso a paso

1. Crea un arreglo `x` con `np.arange(1, 17)` y redimensiónalo como una matriz de 4x4.
2. Genera un arreglo de 10 elementos equidistantes entre 0 y 100 usando `np.linspace()`.
3. Crea una matriz aleatoria de 3x3 con enteros entre 1 y 20 utilizando `np.random.randint()`.
4. Aplica `np.sqrt()` y `np.log()` sobre las matrices creadas (cuando sea posible).
5. Analiza: ¿Qué diferencias notas al aplicar funciones sobre arreglos enteros versus flotantes?


In [2]:
import numpy as np

# Paso 1: Crear un arreglo con np.arange() y redimensionar a 4x4
x = np.arange(1, 17)
matriz_4x4 = x.reshape(4, 4)
print("Matriz 4x4 con np.arange:")
print(matriz_4x4)

# Paso 2: Crear un arreglo con np.linspace()
linspace_array = np.linspace(0, 100, 10)
print("\nArreglo con np.linspace (10 elementos entre 0 y 100):")
print(linspace_array)

# Paso 3: Crear una matriz aleatoria de enteros entre 1 y 20 con np.random.randint()
random_matrix = np.random.randint(1, 21, size=(3, 3))
print("\nMatriz aleatoria 3x3 con enteros entre 1 y 20:")
print(random_matrix)

# Paso 4: Aplicar np.sqrt() y np.log() (donde sea posible)
sqrt_matriz = np.sqrt(matriz_4x4)
log_linspace = np.log(linspace_array[linspace_array > 0])  # evitar log(0)
sqrt_random = np.sqrt(random_matrix)

print("\nRaíz cuadrada de la matriz 4x4:")
print(sqrt_matriz)

print("\nLogaritmo natural de los valores mayores a 0 del linspace:")
print(log_linspace)

print("\nRaíz cuadrada de la matriz aleatoria:")
print(sqrt_random)

# Paso 5: Análisis (comentario)
print("""
🧠 Análisis:
- Las funciones como sqrt y log pueden aplicarse directamente sobre arreglos NumPy sin necesidad de bucles.
- Los resultados sobre arreglos de tipo flotante (como los de linspace) tienden a ser más precisos con funciones matemáticas continuas.
- En arreglos enteros como el generado por randint, sqrt transforma los valores a flotantes, lo cual puede ser útil para ciertos cálculos.
""")


Matriz 4x4 con np.arange:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Arreglo con np.linspace (10 elementos entre 0 y 100):
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]

Matriz aleatoria 3x3 con enteros entre 1 y 20:
[[ 1  4  6]
 [ 4 19  7]
 [14 17 12]]

Raíz cuadrada de la matriz 4x4:
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]
 [3.60555128 3.74165739 3.87298335 4.        ]]

Logaritmo natural de los valores mayores a 0 del linspace:
[2.40794561 3.10109279 3.5065579  3.79423997 4.01738352 4.19970508
 4.35385576 4.48738715 4.60517019]

Raíz cuadrada de la matriz aleatoria:
[[1.         2.         2.44948974]
 [2.         4.35889894 2.64575131]
 [3.74165739 4.12310563 3.46410162]]

🧠 Análisis:
- Las funciones como sqrt y log pueden aplicarse directamente sobre arreglos NumPy sin necesida